spring.application.name=chat-orchestrator
server.port=9100

# MariaDB
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://127.0.0.1:3306/castle_chat_db?useSSL=false&serverTimezone=Asia/Seoul
spring.datasource.username=root
spring.datasource.password=tjdfyd0817

# MyBatis 설정 (필요시)
mybatis.mapper-locations=classpath:mappers/*.xml
mybatis.configuration.map-underscore-to-camel-case=true
# snake_case -> camelCase 자동 매핑.
# mybatis.config-location=classpath:/mybatis-config.xml

# redis 설정
spring.session.store-type=redis
spring.session.redis.namespace=castlechat:session
server.servlet.session.cookie.name=CASTLECHAT_SESSION
server.servlet.session.timeout=30m

spring.data.redis.host=localhost
spring.data.redis.port=6379

# Worker Queue
chat.orchestrator.worker-count=4
chat.orchestrator.queue-capacity=10000

# Gateway delivery URL
ws.gateway.base-url=http://localhost:8090

# gRPC 설정
grpc.server.port=9091

#추후 배포시 true로 변경.
server.servlet.session.cookie.secure=false

server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.same-site=lax

# ===== Actuator / Prometheus =====
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.prometheus.metrics.export.enabled=true

# 1-1. health : 서버 살아있는지 확인
# 1-2. info : 앱 정보
# 1-3. metrics : metric 목록 확인
# 1-4. prometheus : Prometheus가 긁어갈 metric text endpoint
# 2. show-details=always : health에서 DB/Redis 같은 상세 상태도 보여주기
# 3. management.prometheus.metrics.export.enabled=true : Prometheus 형식 metric export 활성화

# < trouble shooting > #
# ISO-8859-1 : 영어/서유럽 문자 중심의 오래된 1바이트 인코딩. 한글 저장 불가.
# UTF-8 : 전세계 문자 대부분 저장 가능. 한글 가능. 요즘 웹/Java/Spring/DB에서 사실상 기본 표준.
# └─>컴퓨터는 글자를 숫자/byte로 저장해야 함. UTF-8은 문자를 byte로 바꾸는 규칙, 즉 문자 인코딩 방식이야.  e.g.) "A":1Byte , "ㅎ":3Byte , "😀":4Byte

